-- Retire optional features without deleting historical payments or company data.
-- All existing business RPCs use this central factor; they now receive base rules.
create or replace function private.specialization_factor(p_company_id uuid,p_key text,p_category text default null)
returns numeric language sql stable set search_path='' as $$ select 1::numeric $$;
revoke all on function private.specialization_factor(uuid,text,text) from public,anon,authenticated;

create or replace function public.set_company_specialization(p_company_id uuid,p_slot_no smallint,p_specialization_code text)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
  perform private.assert_company_owner(p_company_id);
  raise exception 'Spezialisierungen wurden aus dem Spiel entfernt';
end $$;
create or replace function public.upgrade_company_specialization(p_company_id uuid,p_slot_no smallint)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
  perform private.assert_company_owner(p_company_id);
  raise exception 'Spezialisierungen wurden aus dem Spiel entfernt';
end $$;
create or replace function private.complete_specialization_upgrades()
returns integer language sql set search_path='' as $$ select 0 $$;
create or replace function public.get_company_specializations(p_company_id uuid)
returns table(slot_no smallint,specialization_code text,specialization_level smallint,activated_at timestamptz,switch_available_at timestamptz)
language sql stable security invoker set search_path='' as $$ select null::smallint,null::text,null::smallint,null::timestamptz,null::timestamptz where false $$;
create or replace function public.get_company_specialization_progress(p_company_id uuid)
returns table(slot_no smallint,specialization_code text,specialization_level smallint,activated_at timestamptz,switch_available_at timestamptz,upgrade_target_level smallint,upgrade_started_at timestamptz,upgrade_finishes_at timestamptz)
language sql stable security invoker set search_path='' as $$ select null::smallint,null::text,null::smallint,null::timestamptz,null::timestamptz,null::smallint,null::timestamptz,null::timestamptz where false $$;
create or replace function public.get_company_trade_analysis(p_company_id uuid)
returns jsonb language sql stable security invoker set search_path='' as $$ select jsonb_build_object('enabled',false) $$;
revoke all on public.company_specializations,public.company_production_plans from public,anon,authenticated;
do $$ declare j bigint; begin
  for j in select jobid from cron.job where jobname='opencompany-specialization-upgrades' loop
    perform cron.unschedule(j);
  end loop;
end $$;

-- A server-assigned sequence avoids ambiguous read cursors for messages with the
-- same timestamp. Existing messages are numbered in their original display order.
lock table public.chat_messages in access exclusive mode;
alter table public.chat_messages add column read_sequence bigint generated by default as identity;
with numbered as (select id,row_number() over(order by created_at,id) seq from public.chat_messages)
update public.chat_messages m set read_sequence=n.seq from numbered n where m.id=n.id;
alter table public.chat_messages alter column read_sequence set generated always;
select setval(pg_get_serial_sequence('public.chat_messages','read_sequence'),coalesce(max(read_sequence),1),count(*)>0) from public.chat_messages;
create unique index chat_messages_read_sequence_key on public.chat_messages(read_sequence);
create index chat_messages_room_unread_idx on public.chat_messages(room_id,read_sequence desc) where room_id is not null and deleted_at is null;
create index chat_messages_recipient_unread_idx on public.chat_messages(recipient_company_id,sender_company_id,read_sequence desc) where recipient_company_id is not null and deleted_at is null;

create table public.company_chat_reads(
  company_id uuid not null references public.companies(id) on delete cascade,
  target_type text not null check(target_type in ('room','contact')),
  target_id uuid not null,
  last_read_sequence bigint not null check(last_read_sequence>0),
  updated_at timestamptz not null default now(),
  primary key(company_id,target_type,target_id)
);
alter table public.company_chat_reads enable row level security;
revoke all on public.company_chat_reads from public,anon,authenticated;
grant select on public.company_chat_reads to authenticated;
create policy chat_reads_select_own on public.company_chat_reads for select to authenticated
using(exists(select 1 from public.companies c where c.id=company_id and c.owner_user_id=(select auth.uid())));

create or replace function public.get_chat_unread_counts(p_company_id uuid)
returns table(target_type text,target_id uuid,unread_count bigint)
language sql stable security invoker set search_path='' as $$
  with owned as (
    select id from public.companies where id=p_company_id and owner_user_id=(select auth.uid())
  ), incoming as (
    select 'contact'::text target_type,m.sender_company_id target_id,m.read_sequence
    from public.chat_messages m join owned o on o.id=m.recipient_company_id
    where m.room_id is null and m.deleted_at is null and m.sender_company_id<>o.id
    union all
    select 'room'::text,m.room_id,m.read_sequence
    from public.chat_messages m join public.chat_rooms r on r.id=m.room_id and r.is_active
    cross join owned o where m.deleted_at is null and m.sender_company_id<>o.id
  )
  select i.target_type,i.target_id,count(*)
  from incoming i left join public.company_chat_reads r on r.company_id=p_company_id
    and r.target_type=i.target_type and r.target_id=i.target_id
  where i.read_sequence>coalesce(r.last_read_sequence,0)
  group by i.target_type,i.target_id
$$;
revoke all on function public.get_chat_unread_counts(uuid) from public,anon;
grant execute on function public.get_chat_unread_counts(uuid) to authenticated;

-- Clients cannot write arbitrary read cursors. Only a message in an accessible
-- conversation can advance the cursor. GREATEST prevents stale tabs moving it back.
create or replace function private.mark_chat_read(p_company_id uuid,p_target_type text,p_target_id uuid,p_message_id uuid)
returns void language plpgsql security definer set search_path='' as $$
declare v_sequence bigint;
begin
  if auth.uid() is null or not exists(select 1 from public.companies c where c.id=p_company_id and c.owner_user_id=auth.uid()) then
    raise exception 'Keine Berechtigung für diesen Chat' using errcode='42501';
  end if;
  select m.read_sequence into v_sequence from public.chat_messages m where m.id=p_message_id and (
    (p_target_type='room' and m.room_id=p_target_id and exists(select 1 from public.chat_rooms r where r.id=p_target_id and r.is_active))
    or (p_target_type='contact' and m.room_id is null and (
      m.sender_company_id=p_company_id and m.recipient_company_id=p_target_id
      or m.sender_company_id=p_target_id and m.recipient_company_id=p_company_id
    ))
  );
  if v_sequence is null then raise exception 'Nachricht gehört nicht zu diesem Chat' using errcode='42501'; end if;
  insert into public.company_chat_reads(company_id,target_type,target_id,last_read_sequence)
    values(p_company_id,p_target_type,p_target_id,v_sequence)
  on conflict(company_id,target_type,target_id) do update
    set last_read_sequence=greatest(company_chat_reads.last_read_sequence,excluded.last_read_sequence),updated_at=now()
    where company_chat_reads.last_read_sequence<excluded.last_read_sequence;
end $$;
revoke all on function private.mark_chat_read(uuid,text,uuid,uuid) from public,anon;
grant execute on function private.mark_chat_read(uuid,text,uuid,uuid) to authenticated;
create or replace function public.mark_chat_read(p_company_id uuid,p_target_type text,p_target_id uuid,p_message_id uuid)
returns void language sql security invoker set search_path='' as $$
  select private.mark_chat_read(p_company_id,p_target_type,p_target_id,p_message_id)
$$;
revoke all on function public.mark_chat_read(uuid,text,uuid,uuid) from public,anon;
grant execute on function public.mark_chat_read(uuid,text,uuid,uuid) to authenticated;

do $$ begin
  if exists(select 1 from pg_publication where pubname='supabase_realtime') and not exists(
    select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='company_chat_reads'
  ) then alter publication supabase_realtime add table public.company_chat_reads; end if;
end $$;
